// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protos/server.proto

package protos

import (
	fmt "fmt"
	_ "github.com/LTitan/Mebius/pkg/protos/types"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
