log_level = 1
log_path = "/opt/mebius/logs"

[server]
max_recv_byte_size = 1000000
max_send_byte_size = 1000000
port = 8089

[gateway]
max_recv_byte_size = 1000000
max_send_byte_size = 1000000
port = 8090
server_addr = "localhost:8089"
insecure = true

[agent]
heartbeat_period_seconds = 30
server_addr = "localhost:8089"
insecure = true