/*
this is the Mebius Project
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineNamespaceListerExpansion allows custom methods to be added to
// MachineNamespaceLister.
type MachineNamespaceListerExpansion interface{}
