/*
this is the Mebius Project
*/
// Code generated by client-gen. DO NOT EDIT.

package apis

import (
	"net/http"

	apis "github.com/LTitan/Mebius/pkg/apis"
	"github.com/LTitan/Mebius/pkg/clients/clientset/mebius/scheme"
	rest "k8s.io/client-go/rest"
)

type MebiusApisInterface interface {
	RESTClient() rest.Interface
	ClustersGetter
}

// MebiusApisClient is used to interact with features provided by the mebius.io group.
type MebiusApisClient struct {
	restClient rest.Interface
}

func (c *MebiusApisClient) Clusters(namespace string) ClusterInterface {
	return newClusters(c, namespace)
}

// NewForConfig creates a new MebiusApisClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*MebiusApisClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new MebiusApisClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*MebiusApisClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &MebiusApisClient{client}, nil
}

// NewForConfigOrDie creates a new MebiusApisClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MebiusApisClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MebiusApisClient for the given RESTClient.
func New(c rest.Interface) *MebiusApisClient {
	return &MebiusApisClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := apis.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MebiusApisClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
