/*
this is the Mebius Project
*/
// Code generated by informer-gen. DO NOT EDIT.

package pkg

import (
	internalinterfaces "github.com/LTitan/Mebius/pkg/clients/informer/externalversions/internalinterfaces"
	apis "github.com/LTitan/Mebius/pkg/clients/informer/externalversions/pkg/apis"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// Apis provides access to shared informers for resources in Apis.
	Apis() apis.Interface
}

type group struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Apis returns a new apis.Interface.
func (g *group) Apis() apis.Interface {
	return apis.New(g.factory, g.namespace, g.tweakListOptions)
}
